language: cpp
compiler:
  - gcc
# Change this to your needs
install:
    - sudo apt-get update -y
    - sudo apt-get install -y aptitude
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)
    - sudo aptitude install rake
script: 
    - git clone https://github.com/uclmediatools/common.git && cd ./common && ./configure && make
    - cd ../..
    - git clone https://github.com/uclmediatools/tcl-8.0.git && cd ./tcl-8.0/unix && ./configure && make
    - cd ../..
    - git clone https://github.com/uclmediatools/tk-8.0.git && cd ./tk-8.0/unix && ./configure && make
    - cd ../..
    - cd ./vic && ./configure --with-tcl=../tcl-8.0/unix --with-tk=../tk-8.0/unix
    - export LDFLAGS= -L../common/src
    - export INCLUDE_MISC = -I. -Icodec/tmndec -Icodec/tmn-x -Icodec/h263 -Irtp -Irender -Inet -Ivideo -Icodec  -I../common/src
    - make                                                                                                    
branches:
  only:
    - mpeg4
